### ISSUE TITLE
Create a CONTRIBUTING

### ISSUE THREAD

**Issue by emdupre** [FOSH-following-demand/FOSH-following-demand.github.io#18]
It would be nice to have a CONTRIBUTING file here, with information on how to work on GitHub and how to help in making the Jekyll site ! :construction_worker_woman:

**Comment by gooshie** [comment]
@emdupre , this is the first project I've contributed to and I'm new to git and Jekyll. In a couple of weeks I will have plenty of time to work on this project. It sounds like you could have some good ideas for how to setup the infrastructure for the project. Anything you can do to steer me in the right direction so I can be more helpful would be appreciated. Here is a couple of links to the CONTRIBUTING you mentioned. 

### Setting guidelines for [repository contributors](https://help.github.com/articles/setting-guidelines-for-repository-contributors/)
### [Examples](https://help.github.com/articles/setting-guidelines-for-repository-contributors/#examples-of-contribution-guidelines) of contribution guidelines

**Comment by emdupre** [comment]
Hi @gooshie,

It's great to hear that you're interested, and thanks so much for the links ! Yes, CONTRIBUTING guides are really helpful to explain to people (new to the technologies used in the project, or not !) what the "ideal contributing flow" for this particular project looks like. You can see [an example of what I'm thinking of](https://github.com/ME-ICA/tedana/blob/master/CONTRIBUTING.md) at one of the packages I maintain.

This, combined with a roadmap (see #17), should be really helpful in explaining what the project needs right now, and what we as contributors can do to help @amchagas !

**Comment by gooshie** [comment]
Hi @emdupre,

I like your project's CONTRIBUTING guide much better than the examples given in the GitHub help section links I posted. I like the way your project is structured and the supporting documents. I've been coding for many years, and now I'm trying to move up to developer level to be a more effective contributor to open source projects, so I will be studying your project's infrastructure as an example of how to develop a project. Would it be okay with you if I like "boiler-plate" your supporting docs into my personal projects? If it's okay with you and @amchagas I could rework what is useful for this project and put in a PR as a starting point to work from.

**Comment by emdupre** [comment]
Yes of course, feel free to adapt it to your own projects :sparkles: 

I've adapted it for several other projects I contribute to (e.g., [fMRIPrep](https://github.com/poldracklab/fmriprep/blob/master/CONTRIBUTING.md)), if you're looking for ideas on how to remix it. Generally, though, I'm always happy to see helpful contributing guides in use !

If @amchagas decides to move forward with this guide, I imagine we'll need to update it quite a bit to include information on Jekyll. But writing things down is a great way to make sure I understand them, in my experience !

**Comment by amchagas** [comment]
Hi @gooshie and @emdupre , thanks for your inputs! I think the contributing document from @emdupre is pretty good and we could indeed use it as a template for this project. @gooshie if you don't mind, I'll take your offer to work on it? and we contribute once you made a PR?

**Comment by gooshie** [comment]
Hi @amchagas ,
Sure, give me a couple of days. End of the semester crunch time. Two weeks left for me to catch up on my projects. I need to learn Substance Painter in like two days... It's like Photoshop for 3D, so it's like a whole D more complex... 😓

**Comment by amchagas** [comment]
No worries!
Good luck with crunch time ;)

**Comment by gooshie** [comment]
Thanks! 👍

**Comment by emdupre** [comment]
I think this can be closed with the merge of #19 !

**Comment by gooshie** [comment]
I opted to not make any decision on what to add or delete from the initial CONTRIBUTING guide and just search/replace. I think the **Style Guide** section about Python could be removed or changed to something appropriate for this project.

**Comment by amchagas** [comment]
closing this issue so we work on #19. :)
