### ISSUE TITLE
organise the website repository so that we can have every page in different languages

### ISSUE THREAD

**Issue by amchagas** [FOSH-following-demand/FOSH-following-demand.github.io#4]
Since we want to make this project as inclusive as possible it is important to have the website in the same languages as we have the survey. Before we start translating all pages, it would be useful to organize the internal folder structure of the website, so that each language is separated and easy to find in different folders. In steps:
1 - Figure out how Jekyll deals with folders inside the project folder, and if it is simple to have a folder for each language that contains all pages/posts for that specific language, or if it is easier to have a different project for each page and link all of them to a main home page.

**Comment by amchagas** [comment]
Hi @gooshie , 
I tried to put together a page that works with multiple languages. It is not pretty or super automated when it comes to adding more languages, but it is the better I could come up with in short time. 

I appreciate a lot that you want to be involved with the project, and I it will be great to get your input when you have more time! At the same time, I need to push some parts of this right away to get the project moving. That is why I put things together like this for the moment, I hope you don't mind!

**Comment by gooshie** [comment]
Hi @amchagas 
I understand; don't wait for me. I'll jump back in when this semester is over. I'm taking next semester and the summer off to help you and work on my own stuff. I hope to be able to contribute a lot to your project as I think it will look good for my portfolio & resume (what you may call a CV). I am also motivated to help you because of the nature of your projects and all that I have read about you online.

**Comment by amchagas** [comment]
Hey,
great to hear, thanks!  I'm glad that the projects we've been working on are attracting collaborators and are seen with good eyes :) If you don't mind, could we move some of this conversation to email? I think it would be useful for me to learn a bit more about what motivates you (so maybe we can try to inspire more people to collaborate) and how we can work on this long term?

And once again, thanks for all the help so far!

**Comment by gooshie** [comment]
Yes, you read my mind... I'll email you through the email addy you list on the site.

**Comment by gooshie** [comment]
Hi Andre,
This is gooshie.

**Comment by amchagas** [comment]
I think organization structure of the website looks alright. Closing this one
